#!/usr/bin/env sh

set -eu

OPERATION=${1}
MDB_ID=${2}
CONTAINER=my-dev-box-${MDB_ID}
case "${OPERATION}" in
    add)
        if ! command -v realpath >/dev/null 2>&1; then
            realpath() {
                python2 -c 'print(__import__("os").path.realpath(__import__("sys").argv[1]))' "${1}"
            }
        fi
        DATA_DIR=$(dirname "$(realpath "${0}")")/data-${MDB_ID}
        mkdir -p "${DATA_DIR}"
        docker create \
            --name="${CONTAINER}" \
            --hostname="${CONTAINER}" \
            --volume=/var/run/docker.sock:/var/run/docker.sock \
            --volume="${DATA_DIR}:/data" \
            --tty \
            --interactive \
            --privileged \
            --net=host \
            roy2220/my-dev-box
        ;;
    enter)
        docker start --attach --interactive --detach-keys ctrl-\\ "${CONTAINER}"
        ;;
    del)
        docker rm "${CONTAINER}"
        ;;
esac
